### ISSUE TITLE
The dotnet sample doesn't work

### ISSUE THREAD

**Issue by clarkezone** [flightaware/flightxml3_examples#2]
I've signed up for an account, clone the repo put in my API key and UN and it just hangs.  #fail.

**Comment by bovine** [comment]
Our database indicates that your `clarkezone` account on FlightAware only signed up for a FlightXML v2 key. Since these are v3 examples, you must sign up for a v3 key and select a v3 subscription plan.

**Comment by clarkezone** [comment]
Does that cost money?  I’m just trying to kick the tires before I start paying

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by bovine** [comment]
There is a "Bronze" tier on FlightXML3 that provides a limited number of free requests per month.

Please open a thread on our discussion forum at https://discussions.flightaware.com/c/flightaware/flightxml if you have further customer support issues.  Thanks
