### ISSUE TITLE
Spring boot example' error

### ISSUE THREAD

**Issue by TheoBlake** [flightaware/flightxml3_examples#5]
When I request any airportBoards info, e.g. http://localhost:8080/airportBoards?airportCode=ZBAA. The following error occurred:

Error: Your account subscription level does not have access to extended airline and gate information.

I had substituted my username(yaeljiao) and API key in application.properties.

**Comment by bovine** [comment]
Your account (yaeljiao) is only a "Starter" subscription, which does not have access to specify "include_ex_data = true" on the AirportBoards function. You must be "Silver" or higher, as indicated on https://flightaware.com/commercial/flightxml/pricing_class.rvt

**Comment by TheoBlake** [comment]
Thanks for your comment. I think it's better to mark the subscription level for each API in flightxml.
